// FETCH ALL GAMES
export const GAMES_LIST_REQUEST = "GAMES_LIST_REQUEST";
export const GAMES_LIST_SUCCESS = "GAMES_LIST_SUCCESS";
export const GAMES_LIST_FAIL = "GAMES_LIST_FAIL";

// FETCH SINGLE GAME DETAILS
export const GAME_DETAILS_REQUEST = "GAME_DETAILS_REQUEST";
export const GAME_DETAILS_SUCCESS = "GAME_DETAILS_SUCCESS";
export const GAME_DETAILS_FAIL = "GAME_DETAILS_FAIL";

// FETCH ALL CONSOLES
export const CONSOLES_LIST_REQUEST = "CONSOLES_LIST_REQUEST";
export const CONSOLES_LIST_SUCCESS = "CONSOLES_LIST_SUCCESS";
export const CONSOLES_LIST_FAIL = "CONSOLES_LIST_FAIL";

// FETCH SINGLE CONSOLE DETAILS
export const CONSOLE_DETAILS_REQUEST = "CONSOLE_DETAILS_REQUEST";
export const CONSOLE_DETAILS_SUCCESS = "CONSOLE_DETAILS_SUCCESS";
export const CONSOLE_DETAILS_FAIL = "CONSOLE_DETAILS_FAIL";

// FETCH ALL ACCESSORIES
export const ACCESSORIES_LIST_REQUEST = "ACCESSORIES_LIST_REQUEST";
export const ACCESSORIES_LIST_SUCCESS = "ACCESSORIES_LIST_SUCCESS";
export const ACCESSORIES_LIST_FAIL = "ACCESSORIES_LIST_FAIL";

// FETCH SINGLE ACCESSORY DETAILS
export const ACCESSORY_DETAILS_REQUEST = "ACCESSORY_DETAILS_REQUEST";
export const ACCESSORY_DETAILS_SUCCESS = "ACCESSORY_DETAILS_SUCCESS";
export const ACCESSORY_DETAILS_FAIL = "ACCESSORY_DETAILS_FAIL";

// FETCH ALL MERCHANDISES
export const MERCHANDISES_LIST_REQUEST = "MERCHANDISES_LIST_REQUEST";
export const MERCHANDISES_LIST_SUCCESS = "MERCHANDISES_LIST_SUCCESS";
export const MERCHANDISES_LIST_FAIL = "MERCHANDISES_LIST_FAIL";

// FETCH SINGLE MERCHANDISE DETAILS
export const MERCHANDISE_DETAILS_REQUEST = "MERCHANDISE_DETAILS_REQUEST";
export const MERCHANDISE_DETAILS_SUCCESS = "MERCHANDISE_DETAILS_SUCCESS";
export const MERCHANDISE_DETAILS_FAIL = "MERCHANDISE_DETAILS_FAIL";
