// LOGIN & LOGOUT RELATED
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

// REGISTRATION RELATED
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

// USER 'PROFILE DETAILS' RELATED
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

// USER UPDATE PROFILE 'PERSONAL DETAILS' RELATED
export const USER_UPDATE_PERSONAL_REQUEST = "USER_UPDATE_PERSONAL_REQUEST";
export const USER_UPDATE_PERSONAL_SUCCESS = "USER_UPDATE_PERSONAL_SUCCESS";
export const USER_UPDATE_PERSONAL_FAIL = "USER_UPDATE_PERSONAL_FAIL";
export const USER_UPDATE_PERSONAL_RESET = "USER_UPDATE_PERSONAL_RESET";

// USER UPDATE PROFILE 'PASSWORD' RELATED
export const USER_UPDATE_PASSWORD_REQUEST = "USER_UPDATE_PASSWORD_REQUEST";
export const USER_UPDATE_PASSWORD_SUCCESS = "USER_UPDATE_PASSWORD_SUCCESS";
export const USER_UPDATE_PASSWORD_FAIL = "USER_UPDATE_PASSWORD_FAIL";
export const USER_UPDATE_PASSWORD_RESET = "USER_UPDATE_PASSWORD_RESET";

// USER UPDATE PROFILE 'DELIVERY ADDRESS' RELATED
export const USER_UPDATE_ADDRESS_REQUEST = "USER_UPDATE_ADDRESS_REQUEST";
export const USER_UPDATE_ADDRESS_SUCCESS = "USER_UPDATE_ADDRESS_SUCCESS";
export const USER_UPDATE_ADDRESS_FAIL = "USER_UPDATE_ADDRESS_FAIL";
export const USER_UPDATE_ADDRESS_RESET = "USER_UPDATE_ADDRESS_RESET";
